# Prompt
# export PS1='\[\033[0;32m\]\h\[\033[0;36m\] \w\[\033[00m\]: '

# Silly Apple ls
alias ls='ls -G'

alias free='free -m'
alias lsa='ls -la'
alias rm='rm -rf'
alias vi='vim'
alias svm='vim'
alias ms='python manage.py shell'
alias follow='tail -n 100 -f'

# pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true
# cache pip-installed packages to avoid re-downloading
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

pips(){
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}

export WORKON_HOME=~/envs
source /usr/local/bin/virtualenvwrapper.sh
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true

