" Lots from
" https://realpython.com/blog/python/vim-and-python-a-match-made-in-heaven/

call plug#begin('~/.vim/plugged')

Plug 'vim-syntastic/syntastic'
Plug 'tomlion/vim-solidity'

call plug#end()

"Plugin 'tmhedberg/SimpylFold'
"Plugin 'vim-scripts/indentpython.vim'
"Plugin 'Valloric/YouCompleteMe'
"Plugin 'scrooloose/syntastic'
"Plugin 'nvie/vim-flake8'
"Plugin 'altercation/vim-colors-solarized'
"Plugin 'scrooloose/nerdtree'
"Plugin 'jistr/vim-nerdtree-tabs'
"Plugin 'ctrlpvim/ctrlp.vim'
"Plugin 'tpope/vim-fugitive'
"Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}

" vim-syntastic config
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

filetype plugin indent on

let mapleader=" "
let python_highlight_all=1
syntax on

" Solarized config
"set background=dark
"let g:solarized_termtrans = 1
"colorscheme solarized
"call togglebg#map("<F5>")

" NerdTree config
let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree

" Enable folding
set foldmethod=indent
set foldlevel=99

" Enable folding with spacebar
nnoremap <space> za

" PEP-8
au FileType python
    \ setlocal tabstop=4 softtabstop=4 shiftwidth=4 textwidth=79 
    \ expandtab autoindent fileformat=unix 

" Web Dev
au FileType javascript,html,css,json
    \ setlocal tabstop=2 softtabstop=2 shiftwidth=2

" Flag whitespace
"au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/

set encoding=utf-8

" YouCompleteMe customization
let g:ycm_autoclose_preview_window_after_completion=1
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>

"python with virtualenv support
py3 << EOF
import os
import sys
if 'VIRTUAL_ENV' in os.environ:
  project_base_dir = os.environ['VIRTUAL_ENV']
  activate_this = os.path.join(project_base_dir, 'bin/activate_this.py')
  exec(compile(open(activate_this,'rb').read(), activate_this, 'exec'), dict(__file__=activate_this))
EOF
