# p10k
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ENV Vars
export EDITOR=vim
export VISUAL=vim
export PAGER=less
export LANG=en_US.UTF-8

# Prezto
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Snappy escape
export KEYTIMEOUT=1

# Aliases
alias lsa="ls -la"
alias rm="rm -rf"
alias m="python manage.py"
alias ht="sudo htop"

# mappings
bindkey '^K' kill-whole-line
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward
bindkey -M vicmd "^[" vi-add-next

# History
setopt INC_APPEND_HISTORY        # Share history between all sessions.

HISTSIZE=50000                   # The maximum number of events to save in the internal history.
SAVEHIST=50000                   # The maximum number of events to save in the history file.
